version: 2
jobs:
  build:
    docker:
       - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: NPM Install
          command: npm install

      - run:
          name: NPM Version
          command: npm -v

      - run:
          name: NPM Test
          command: npm test

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:de9a58b8-ede6-45e8-9f8b-a8fe14c2a83a@git.heroku.com/afternoon-lowlands-60297.git master