version: 2
jobs:
  build:
    docker:
       - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install NPM
          command: npm install

      - run:
          name: NPM Version
          command: npm -v

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Greeting
          command: echo Hello, world.